### ISSUE TITLE
Changer la taille des icones

### ISSUE THREAD

**Issue by mistergraphx** [mistergraphx/spip_socialshare#1]
> Bonjour,
> Merci pour votre partage !(cf discussion récente sur forum plugin socialtag)
> J’utilise fort bien socialshare et j’aimerai pouvoir modifier la taille et les couleurs des icônes.
> Je ne maîtrise pas la technique SVG Sprite icons que vous utilisez.
> Je me demande à quoi est utile le fichier socialshare.css ? comment le surcharger ?
> Merci pour votre éclairage
> Jean-Pierre

**Comment by mistergraphx** [comment]
Changer la taille des icone est relativement simple si on utilise que le sprite svg :

il suffit comme pour une police d'icone de changer la taille de la police sur le selecteur css de l'icone.

dans une feuille de style personelle

```css
/* Changer la taille des icone svg */
.svg .s-icon {
  font-size: 2rem; /* la taille des icones pour le sprite svg se régle avec la propriété font-size */
}
.s-icon,
.no-svg .s-icon {
  width: 45px; /* pour les images png utilisées en cas de non gestion du svg par le navigateur : on utilise width/height */
  height:45px;
}
```

Pour changer la couleur des icone  :

```css

.svg .s-icon {
  background-color: blue; /* pour changer la couleur de toutes les icones svg */
}
/* Pour changer une icone spécifique */
.s-icon-twitter{
  background-color: blue;
}
```

on peut aussi ne pas charger les css depuis la config du plugin et gérer les css depuis un theme. C'est ce que je fais le plus souvent.
